export enum NotificationType {
  VISIT_ACCEPTED = 'VISIT_ACCEPTED',
  VISIT_REFUSED = 'VISIT_REFUSED',
  VISIT_REMINDER_J2 = 'VISIT_REMINDER_J2',
  VISIT_REMINDER_J1 = 'VISIT_REMINDER_J1',
  VISIT_REMINDER_H2 = 'VISIT_REMINDER_H2',
  VISIT_REMINDER_H1 = 'VISIT_REMINDER_H1',
  VISIT_REMINDER_H30 = 'VISIT_REMINDER_H30',
  // Collector reminders
  VISIT_REMINDER_COLLECTOR_J2 = 'VISIT_REMINDER_COLLECTOR_J2',
  VISIT_REMINDER_COLLECTOR_J1 = 'VISIT_REMINDER_COLLECTOR_J1',
  VISIT_REMINDER_COLLECTOR_H2 = 'VISIT_REMINDER_COLLECTOR_H2',
  VISIT_REMINDER_COLLECTOR_H1 = 'VISIT_REMINDER_COLLECTOR_H1',
  VISIT_REMINDER_COLLECTOR_H30 = 'VISIT_REMINDER_COLLECTOR_H30',
}



